version: "3.3"
services:
  app:
    build: .
    environment:
      HOST_UID: 1000
    volumes:
      - "./app:/opt/app"
    ports:
      - 3000:3000
    command: bash -c "yarn install && yarn start"
    stdin_open: true
    tty: true
